scrapers:
  - name: TerminalWest
    url: https://terminalwestatl.com/
    item: div.c-axs-event-card__wrapper
    fields:
      - name: "location"
        value: Terminal West
      - name: "city"
        value: "Atlanta"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://terminalwestatl.com/
      - name: title
        type: text
        location:
          - selector: div.c-axs-event-card__title
      - name: url
        type: url
        location:
          - attr: href
            selector: a.c-axs-event-card__header
      - name: imageUrl
        type: url
        location:
          - selector: img.u-img-respond
            attr: src
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
              time: true
            location:
              selector: p.c-axs-event-card__date--showtime7121
              entire_subtree: true
            layout:
              - Mon, Jan 2, 2006 15:04 PM
        date_location: America/New_York
        date_language: en_US
    render_js: true
    page_load_wait: 4000

  - name: CenterStage
    url: https://www.centerstage-atlanta.com/
    item: body.csa-body.home.page.page-id-70.page-template-default > div.csa-site-wrap > div.csa-main-content > section.content-area > main.site-main > section.events-section > div.events-listing > div.events-listing__inner > div.event-item.popup-event
    fields:
      - name: "city"
        value: "Atlanta"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.centerstage-atlanta.com/
      - name: title
        type: text
        location:
          - selector: div.event-action > div.event-item-content > div.event-info > h3.event-name
      - name: location
        type: text
        location:
          - selector: div.event-action > div.event-item-content > div.event-info > h4.event-venue
      - name: url
        type: url
        location:
          - selector: a.event-link
            attr: href
      - name: imageUrl
        type: url
        location:
          - selector: img
            attr: src
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.event-details-visible > div.event-show_time
              regex_extract:
                exp: "[0-9]{1,2}:[0-9]{2} [ap]m"
                index: -1
            layout:
              - 15:04 pm
          - covers:
              day: true
              month: true
            location:
              selector: div.event-action > div.event-item-content > div.event-info > span.event-date
            layout:
              - Mon Jan 2
        date_location: America/New_York
        date_language: en_US
    render_js: true
    interaction:
      - type: click
        selector: "#main > section.events-section > div.events-listing > div > div.view-more-shows-wrap > a"
        count: 4
        delay: 1000

  - name: VarietyPlayhouse
    url: https://www.variety-playhouse.com/
    item: div.c-axs-event-card__wrapper
    fields:
      - name: "location"
        value: Variety Playhouse
      - name: "city"
        value: "Atlanta"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.variety-playhouse.com/
      - name: title
        type: text
        location:
          - selector: div.c-axs-event-card__title
      - name: url
        type: url
        location:
          - attr: href
            selector: a.c-axs-event-card__header
      - name: imageUrl
        type: url
        location:
          - selector: img.u-img-respond
            attr: src
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
              time: true
            location:
              selector: div.c-axs-event-card__date.c-axs-event-card__date7215.u-font-20 > p.c-axs-event-card__date--showtime7215
              entire_subtree: true
            layout:
              - Mon, Jan 2, 2006 15:04 PM
        date_location: America/New_York
        date_language: en_US
    render_js: true
    page_load_wait: 3000
