scrapers:
  - name: BirdsEye
    url: https://birdseye.ch/index.php?p=events&l=en
    item: body > div.container > div.grid > div.pagecontent
    fields:
      - name: "location"
        value: "the Bird's Eye jazz club"
      - name: city
        value: "Basel"
      - name: "country"
        value: "Switzerland"
      - name: "type"
        value: "concert"
      - name: url
        type: url
        value: https://birdseye.ch/index.php?p=events
      - name: sourceUrl
        type: url
        value: https://birdseye.ch/index.php?p=events
      - name: imageUrl
        type: url
        location:
          - selector: div.grid > img.event-img
            attr: src
      - name: icalUrl
        type: url
        location:
          - selector: ul.ical > a
        can_be_empty: true
      - name: date
        type: date
        on_subpage: icalUrl
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: select > option
              regex_extract:
                exp: "[0-9]{2}\\.[0-9]{2}\\.[0-9]{4}"
            layout: ["2.1.2006"]
          - covers:
              time: true
            location:
              default: "20:30"
            layout:
              - "15:04"
        date_location: "Europe/Berlin"
      - name: title
        type: text
        location:
          - selector: h2.event-desc > strong
      - name: comment
        type: text
        location:
          - selector: div.grid > p.lineup
        can_be_empty: true

  - name: Humbug
    url: https://www.humbug.club/programm
    item: body > div.content-wrapper > div.programm-grid > a
    fields:
      - name: "location"
        value: "Humbug"
      - name: city
        value: "Basel"
      - name: "country"
        value: "Switzerland"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.humbug.club/programm
      - name: title
        type: text
        location:
          - selector: div.grid-item > div.event-title > div.event-title-wrapper > h4
      - name: date
        type: date
        components:
          - covers:
              day: true
            location:
              selector: div.grid-item > div.event-title > p.event-date
              regex_extract:
                exp: "[0-9]{2}"
                index: 0
            layout:
              - 2
          - covers:
              month: true
            location:
              selector: div.grid-item > div.event-title > p.event-date
              regex_extract:
                exp: "[0-9]{1,2}"
                index: 1
            layout:
              - 1
          - covers:
              year: true
            location:
              selector: div.grid-item > div.event-title > p.event-date
              regex_extract:
                exp: "[0-9]{1,4}"
                index: 2
            layout:
              - 06
              - 2006
          - covers:
              time: true
            location:
              default: "20:00"
            layout:
              - "15:04"
        date_location: "Europe/Berlin"
      - name: url
        type: url
        location:
          - attr: href
      - name: comment
        type: text
        can_be_empty: true
        location:
          - selector: div.grid-item > div.event-title > div.event-title-wrapper > h4
            child_index: 2
    filters:
      - field: "title"
        exp: ".*(?i)(abgesagt).*"
        match: false
      - field: "title"
        exp: "Infos zum geschlossenen HUMBUG"
        match: false
      - field: title
        exp: ".*UshaltBAR.*"
        match: false
      - field: date
        exp: "> now"
        match: true

  - name: ParterreOne
    url: "https://parterre-one.ch/klub-kultur/"
    item: "div.col-12.col-md-6.animation-fade"
    fields:
      - name: "location"
        value: "Parterre One"
      - name: "city"
        value: "Basel"
      - name: country
        value: Switzerland
      - name: "sourceUrl"
        value: "https://www.parterre.net/de/musik-kultur/one-music/programm?category=1"
      - name: "title"
        location:
          selector: "div > h3"
      - name: "type"
        type: text
        location:
          selector: "div > span.card-categories-subheader"
        transform:
          - type: regex-replace
            regex: "Konzert"
            replace: concert
          - type: regex-replace
            regex: "Party"
            replace: party
      - name: "url"
        type: "url"
        location:
          selector: "a"
      - name: imageUrl
        type: url
        location:
          selector: "div > img"
          attr: src
      - name: "date"
        type: "date"
        on_subpage: "url"
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: "div > div:nth-child(1) > span.fs-35.fw-light"
            layout: ["02.01.2006"]
          - covers:
              time: true
            location:
              selector: "div > div:nth-child(3) > span.fs-35.fw-light.text-uppercase"
            layout: ["15:04 Uhr"]
        date_location: "CET"

  - name: KaserneBasel
    url: https://kaserne-basel.ch/en
    item: body > div > main > div.container > div.index > details
    fields:
      - name: "location"
        value: Kaserne Basel
      - name: "city"
        value: "Basel"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://kaserne-basel.ch/en"
      - name: eventType
        type: text
        location:
          - selector: summary > div.event-container > div.event-content > div.category
      - name: comment
        can_be_empty: true
        type: text
        location:
          - selector: summary > div.event-container > div.event-content > h3.subtitle
      - name: title
        type: text
        location:
          - selector: summary > div.event-container > div.event-content > h2
      - name: url
        type: url
        location:
          - selector: a.image-link
            attr: href
      - name: imageUrl
        type: url
        location:
          - selector: a.image-link > figure > img
            attr: src
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
            location:
              selector: summary > div.event-container > div.event-content > time
              regex_extract:
                exp: "[0-9]{1,2}\\. [A-Za-z]+"
            layout:
              - "2. January"
          - covers:
              time: true
            location:
              selector: div > section > span > time:nth-child(1)
            layout:
              - "15:04"
        date_location: CET
        date_language: en_US
        guess_year: true
    fetcher:
      type: dynamic
    filters:
      - field: "eventType"
        exp: "Theatre"
        match: false
      - field: "eventType"
        exp: ".*Lecture.*"
        match: false
      - field: "eventType"
        exp: "Workshop"
        match: false

  - name: Offbeat
    url: https://www.offbeat-concert.ch/
    item: body.resource-1.template-1 > div.section > div.row > div.columns.medium-10.medium-offset-2.small-12 > div.event__listing > div.event__item > a
    fields:
      - name: "city"
        value: "Basel"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.offbeat-concert.ch/
      - name: location
        type: text
        location:
          - selector: span.nowrap
            regex_extract:
              exp: "[A-Z]+[A-Z ]+"
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: span.nowrap
              regex_extract:
                exp: "[0-9]{1,2}. [A-Z][a-z]+ [0-9]{4}"
            layout: ["2. January 2006"]
          - covers:
              time: true
            location:
              selector: span.nowrap
              regex_extract:
                exp: "[0-9]{2}:[0-9]{2}"
            layout: ["15:04"]
        date_language: de_DE
        date_location: CET
      - name: title
        type: text
        location:
          - selector: h2.event__title
            entire_subtree: true
      - name: url
        type: url
        location:
          - attr: href
