scrapers:
  - name: Gretchen
    url: https://www.gretchen-club.de/
    item: body.normal.start > div.block > div.start > div > div.dates > div.gig
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Berlin"
      - name: "country"
        value: "Germany"
      - name: "location"
        value: "Gretchen"
      - name: "sourceUrl"
        value: "https://www.gretchen-club.de/"
      - name: title
        location:
          selector: div.gig_main > div.scroll.nano > div.text.nano-content > span.title > h2 > a
      - name: url
        type: url
        location:
          selector: div.gig_main > div.scroll.nano > div.text.nano-content > span.title > h2 > a
          attr: href
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.gig_top > span.date > strong
            layout: ["2.1.2006"]
          - covers:
              time: true
            location:
              selector: div.gig_top > span.date
              regex_extract:
                exp: "Show: [0-9\\.]+"
              entire_subtree: true
            layout: ["Show: 15", "Show: 15.04"]
        date_location: "Europe/Berlin"
    filters:
      - field: "title"
        exp: ".*CANCELLED"
        match: false

  - name: HuxleysNeueWelt
    url: https://huxleysneuewelt.de/events
    item: ul > li.event-item
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Berlin"
      - name: "country"
        value: "Germany"
      - name: "location"
        value: "Huxleys Neue Welt"
      - name: "sourceUrl"
        value: https://huxleysneuewelt.com/shows
      - name: title
        type: text
        location:
          - selector: div.details > .eventname
      - name: url
        type: url
        location:
          - attr: href
            selector: a
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.details > div.time
              regex_extract:
                exp: "Beginn: [0-9]{2}[:\\.]{1}[0-9]{2}"
            layout:
              - "Beginn: 15:04"
              # - "Einlass: 15.04"
          - covers:
              month: true
            location:
              selector: div.date > span
            layout:
              - Jan
            transform:
              - type: regex-replace
                regex: Mrz
                replace: Mär
          - covers:
              day: true
            location:
              selector: div.date
            layout:
              - "2"
        date_location: CET
        date_language: de_DE
        guess_year: true

  - name: Metropol
    url: https://metropol-berlin.de/events
    item: div.wrapper > div.pagecontent > div.container.grid-container.grid-parent.hfeed.site > div.site-content > div.content-area.grid-100.grid-parent.mobile-grid-100.tablet-grid-100 > main.site-main > article.has-post-thumbnail.page.post-11.status-publish.type-page > div.inside-article > div.entry-content > div > div.em.em-view-container > div.em-events-list.em-list > ul.eventlist > li.event
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Berlin"
      - name: "country"
        value: "Germany"
      - name: "location"
        value: "Metropol"
      - name: "sourceUrl"
        value: https://metropol-berlin.de/events
      - name: title
        type: text
        location:
          - selector: div.main:nth-child(2) > a.title > h2.artist
      - name: url
        type: url
        location:
          - selector: div.main:nth-child(2) > a.title
            attr: href
      - name: comment
        type: text
        location:
          - selector: div.date > ul.event-categories > li > a
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.date > span.time
            layout:
              - "15:04"
          - covers:
              month: true
              year: true
            location:
              selector: div.date > span.monthyear
            layout:
              - Jan. 2006
          - covers:
              day: true
            location:
              selector: div.date > span.day
            layout:
              - 2/
        date_location: CET
        date_language: de_DE

  - name: Peppi Guggenheim
    url: https://www.peppi-guggenheim.de/?post_type=tribe_events
    item: div.tribe-common-g-col.tribe-events-calendar-list__event-details
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Berlin"
      - name: "country"
        value: "Germany"
      - name: "location"
        value: "Gretchen"
      - name: "sourceUrl"
        value: "https://www.peppi-guggenheim.de/?post_type=tribe_events"
      - name: title
        type: text
        location:
          - selector: h3.tribe-common-h4--min-medium.tribe-common-h6.tribe-events-calendar-list__event-title > a.tribe-common-anchor-thin.tribe-events-calendar-list__event-title-link
      - name: comment
        location:
          - selector: div > p
        can_be_empty: true
      - name: url
        type: url
        location:
          - selector: h3.tribe-common-h4--min-medium.tribe-common-h6.tribe-events-calendar-list__event-title > a.tribe-common-anchor-thin.tribe-events-calendar-list__event-title-link
            attr: href
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              time: true
            location:
              selector: div.tribe-common-b2.tribe-events-calendar-list__event-datetime-wrapper > time.tribe-events-calendar-list__event-datetime > span.tribe-event-date-start
            layout:
              - January 2 @ 15:04
        date_location: CET
        date_language: de_DE
        guess_year: true

  - name: Lido
    url: https://www.lido-berlin.de/
    item: div.page > div.event-list > article.event-ticket
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Berlin"
      - name: "country"
        value: "Germany"
      - name: "location"
        value: "Lido"
      - name: "sourceUrl"
        value: "https://www.lido-berlin.de/"
      - name: eventType
        type: text
        location:
          - selector: div.event-ticket__type > div.event-ticket__type__label
        hide: true
        can_be_empty: true
      - name: title
        type: text
        location:
          - selector: div.event-ticket__content > h1.event-ticket__content__title > a
      - name: url
        type: url
        location:
          - selector: div.event-ticket__content > h1.event-ticket__content__title > a
            attr: href
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.event-ticket__meta > div.event-ticket__meta__times > div.event-ticket__meta__times__time:nth-child(2) > div.event-ticket__meta__times__time__value
            layout:
              - "15:04"
          - covers:
              day: true
              month: true
            location:
              selector: div.event-ticket__meta.event-ticket__meta--mobile > div.event-ticket__meta__date > div.event-ticket__meta__date__day-month
            layout:
              - 2.1.
          - covers:
              year: true
            location:
              selector: div.event-ticket__meta.event-ticket__meta--desktop > div.event-ticket__meta__date > div.event-ticket__meta__date__year
            layout:
              - "2006"
        date_location: CET
    filters:
      - field: eventType
        match: false
        exp: Party
