scrapers:
  - name: Bierhuebeli
    url: "https://bierhuebeli.ch/konzerte/"
    item: div.elementor-widget-container > div.js-wpv-view-layout.js-wpv-layout-responsive.js-wpv-view-layout-11026 > a.datumlink
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Bern"
      - name: country
        value: Switzerland
      - name: "location"
        value: "Bierhuebeli"
      - name: "sourceUrl"
        value: "https://bierhuebeli.ch/konzerte/"
      - name: url
        type: url
        location:
          attr: href
      - name: title
        type: text
        location:
          selector: div.datumswrapper > div.event-upperpart > div.eventtitel
      - name: comment
        type: text
        can_be_empty: true
        location:
          selector: div.datumswrapper > div.byline
      - name: date
        type: date
        on_subpage: url
        components:
          - covers:
              day: true
              month: true
              year: true
            layout: ["Mon, 2.1.06"]
            location:
              selector: div.billboard-big > div > div.billboard-datum > font
          - covers:
              time: true
            location:
              selector: div.eventinfos > b:nth-child(3)
            layout: ["15:04"]
        date_language: de_DE
        date_location: "Europe/Berlin"

  - name: Gaskessel
    url: https://gaskessel.ch/programm/
    item: article.eventpreview
    fields:
      - name: "location"
        value: "Gaskessel"
      - name: "city"
        value: "Bern"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://gaskessel.ch/programm/"
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: a.previewlink > span.eventdatum
            layout: ["Mon 2.1.06"]
          - covers:
              time: true
            location:
              selector: div.contentbox > div.content > div.textblock > div.infobox > div.table > div.trow > div.tcell
              node_index: 1
            layout: ["15:04"]
        date_location: "Europe/Berlin"
        date_language: "de_DE"
      - name: title
        type: text
        location:
          selector: a.previewlink > h2.eventname
          entire_subtree: true
      - name: url
        type: url
        location:
          selector: div.contentbox > div.content > div.textblock > div.infobox > div.btns > a.ticketlink
          attr: href
      - name: comment
        type: text
        location:
          selector: div.contentbox > div.content > div.textblock > div.text > p
        can_be_empty: true

  - name: Dachstock
    url: https://www.dachstock.ch/events
    item: div.event-teaser-info
    fields:
      - name: "location"
        value: "Dachstock"
      - name: "city"
        value: "Bern"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.dachstock.ch/events
      - name: "date"
        type: "date"
        components:
          - covers:
              day: true
              month: true
              year: true
              time: true
            location:
              selector: a.event-date
              regex_extract:
                exp: "[0-9]{2}.[0-9]{2}.[0-9]{4} - [0-9]{2}:[0-9]{2}"
            layout: ["02.01.2006 - 15:04"]
        date_location: "Europe/Berlin"
        date_language: "de_DE"
      - name: "url"
        type: url
        location:
          selector: div.event-teaser-top > a
          attr: href
      - name: "title"
        type: text
        location:
          selector: div.artist-name
          all_nodes: true
          separator: ", "
      - name: "comment"
        type: text
        location:
          selector: div.event-title
        can_be_empty: true

  # - name: BeJazz
  #   url: https://www.bejazz.ch/de/bejazz-aktueller-jazz-in-bern/programm-80.html
  #   item: body > div.bjz-wrapper.ym-wrapper > div.wbox.ym-wrapper-inner > div.bjz-action.ym-column > div.bjz-action-marginal.ym-col1 > div.ym-gbox > div.bjz-component-marginal > div.bjz-component-marginal-inner > div.bjz-component-marginal-items > ul > li > a.bjz-component-marginal-eventitem
  #   fields:
  #     - name: "city"
  #       value: "Bern"
  #     - name: country
  #       value: Switzerland
  #     - name: "type"
  #       value: "concert"
  #     - name: "sourceUrl"
  #       value: https://www.bejazz.ch/de/bejazz-aktueller-jazz-in-bern/programm-80.html
  #     - name: title
  #       type: text
  #       location:
  #         - selector: div.info > div.name
  #     - name: location
  #       type: text
  #       location:
  #         - selector: div.info > div.location
  #           regex_extract:
  #             exp: "[^: ]+[^:]+"
  #             index: -1
  #     - name: url
  #       type: url
  #       location:
  #         - attr: href
  #     - name: date
  #       type: date
  #       on_subpage: url
  #       components:
  #         - covers:
  #             day: true
  #           location:
  #             selector: div.ym-gbox > div.date
  #           layout:
  #             - "2"
  #         - covers:
  #             month: true
  #           location:
  #             selector: div.ym-gbox > div.month
  #           layout:
  #             - Jan
  #         - covers:
  #             year: true
  #           location:
  #             selector: div.ym-gbox > div.year
  #           layout:
  #             - "2006"
  #         - covers:
  #             time: true
  #           location:
  #             selector: div > p.bjz-t-overline > span
  #           layout:
  #             - 15:04 Uhr
  #       date_location: CET
  #       date_language: de_DE

  - name: MahoganyHall
    url: https://www.mahogany.ch/konzerte
    item: body > div > div > div.column > div.view.view-display-id-page.view-dom-id-16ec81cc9a231bf191b8f75dfe36b39d.view-id-konzerte.view-konzerte > div.view-content > div.views-row
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Bern"
      - name: country
        value: Switzerland
      - name: "location"
        value: "Mahagany Hall"
      - name: "sourceUrl"
        value: "https://www.mahogany.ch/konzerte"
      - name: comment
        type: text
        location:
          - selector: div.views-field.views-field-field-teasertext:nth-child(4) > p.field-content
      - name: style
        type: text
        location:
          - selector: div.views-field.views-field-field-subtitle > h5.field-content
      - name: title
        type: text
        location:
          - selector: span.views-field.views-field-title:nth-child(2) > h2.field-content > a
      - name: url
        type: url
        location:
          - selector: span.views-field.views-field-title:nth-child(2) > h2.field-content > a
            attr: href
      - name: imageUrl
        type: url
        location:
          - selector: div.field.field-name-field-titelbild.field-type-image.field-label-hidden > div > div > img
            attr: src
        on_subpage: url
      - name: date
        type: date
        components:
          - covers:
              year: true
              month: true
              day: true
            location:
              selector: span.views-field.views-field-field-tueroeffnung > div.concert-tueroeffnung.field-content
              regex_extract:
                exp: "[0-9]{1,2}. .* [0-9]{4}"
            layout: ["2. January 2006"]
          - covers:
              time: true
            location:
              selector: span.views-field.views-field-field-tueroeffnung > div.concert-tueroeffnung.field-content
              regex_extract:
                exp: "[0-9]{2}.[0-9]{2} Uhr"
            layout: ["15.04 Uhr"]
        date_language: de_DE
        date_location: "Europe/Berlin"

  - name: OnoBern
    url: https://www.onobern.ch/homepage/
    item: body > div > div.et-boc > div > div > article.hentry.page.post-19.status-publish.type-page > div.entry-content > div.et-l.et-l--post > div.et_builder_inner_content.et_pb_gutters3 > div.et_pb_section.et_pb_section_1.et_section_regular > div.et_pb_row.et_pb_row_3 > div.et-last-child.et_pb_column.et_pb_column_2.et_pb_column_4_4.et_pb_css_mix_blend_mode_passthrough > div.et_pb_bg_layout_light.et_pb_module.et_pb_text.et_pb_text_1.et_pb_text_align_left > div.et_pb_text_inner > div.ajde_evcal_calendar.box_2.list_cal.ul > div.evcal_list_month.eventon_events_list.sep_months > div.sep_month_events > div.event.eventon_list_event.evo_eventtop
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Bern"
      - name: country
        value: Switzerland
      - name: "location"
        value: "ONO Das Kulturlokal"
      - name: "sourceUrl"
        value: "https://www.onobern.ch/homepage/"
      - name: comment
        type: text
        location:
          - selector: p.desc_trig_outter > a.desc_trig.evcal_list_a.hasFtIMG.sin_val > span.evcal_desc.evo_info.hide_eventtopdata:nth-child(3) > span.evo_below_title:nth-child(3) > span.evcal_event_subtitle
      - name: title
        type: text
        location:
          - selector: p.desc_trig_outter > a.desc_trig.evcal_list_a.hasFtIMG.sin_val > span.evcal_desc.evo_info.hide_eventtopdata:nth-child(3) > span.evcal_desc2.evcal_event_title:nth-child(2)
      - name: date
        type: date
        components:
          - covers:
              year: true
            location:
              selector: #evcal_cur
              regex_extract:
                exp: "[0-9]{4}"
            layout: ["2006"]
          - covers:
              month: true
            location:
              selector: p.desc_trig_outter > a.desc_trig.evcal_list_a.hasFtIMG.sin_val > span.evcal_cblock:nth-child(2) > span.evo_start > em.month:nth-child(3)
            layout: ["Jan.", "January"]
          - covers:
              day: true
            location:
              selector: p.desc_trig_outter > a.desc_trig.evcal_list_a.hasFtIMG.sin_val > span.evcal_cblock:nth-child(2) > span.evo_start > em.date:nth-child(2)
            layout: ["02"]
          - covers:
              time: true
            location:
              selector: p.desc_trig_outter > a.desc_trig.evcal_list_a.hasFtIMG.sin_val > span.evcal_cblock:nth-child(2) > span.evo_start > em.time:nth-child(4)
            layout: ["15:04"]
        date_language: de_DE
        date_location: "Europe/Berlin"
      - name: url
        type: url
        location:
          - selector: div.evo_event_schema > a
            attr: href
      - name: imageUrl
        type: url
        location:
          - selector: .ev_ftImg
            attr: data-bg
    filters:
      - field: comment
        exp: "Privat"
        match: false

