scrapers:
  - name: Scullers
    url: https://scullersjazz.com/upcoming-events/
    item: div.blackBack.cf.musicidb-events-integration > div.cf.inside > div.musicidb-tabs > div.current.musicidb-tab > div.musicidb-tabs.ui-tabs-nav > div.musicidb-tab > ul.cf.eventsList > li.cf.listEvent.listItem.summaryContent
    fields:
      - name: type
        value: concert
      - name: city
        value: Boston
      - name: country
        value: United States
      - name: sourceUrl
        value: https://scullersjazz.com/upcoming-events/
      - name: location
        value: Scullers
      - name: date
        type: date
        components:
          - covers:
              month: true
            location:
              selector: h3.date > span.monthName:nth-child(2)
            layout: ["Jan"]
          - covers:
              day: true
            location:
              selector: h3.date > span.dayNum
            layout: ["2"]
          - covers:
              year: true
            location:
              selector: h3.date > span.yearNum
            layout: ["2006"]
          - covers:
              time: true
            location:
              selector: div.listingBody > div.h4.subtitleEvent
              regex_extract:
                exp: "[0-9]{1}(\\s)?pm"
            layout: ["15 pm", "15pm"]
        date_location: America/New_York
      - name: url
        type: url
        location:
          - selector: div.eventPosterArea > a
            attr: href
      - name: title
        type: text
        location:
          - selector: div.listingBody > h3 > a
    render_js: true
    filters:
      - field: date
        exp: "> now"
        match: true
