scrapers:
  - name: Majestic
    url: http://www.majestic.sk/program
    item: div.elementor-align-left.elementor-align-left.elementor-widget-tootoot-event-list > div.elementor-widget-container > div.tt-layout-tiles > div.tt-entity-list-container.tt-event-list > div.tt-evt-li > div.tt-evt-li__event-info
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Bratislava"
      - name: "location"
        value: "Majestic"
      - name: "sourceUrl"
        value: "http://www.majestic.sk/program"
      - name: title
        type: text
        location:
          - selector: a.tt-evt-li__name > span.clickable--ProfileName
      - name: url
        type: url
        location:
          - selector: a.tt-evt-li__name
            attr: href
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
              time: true
            location:
              selector: div.elementor-repeater-item-ff3fa99.tt-evt-li__sub-info.tt-evt-li__sub-info--BeginDate
              regex_extract:
                exp: "[0-9\\.@: ]+"
            layout:
              - "2.1.2006 @15:04"
        date_location: CET
