scrapers:
  - name: Ebullition
    url: https://www.ebull.ch/fr
    item: body > div.col-md-12.contenaire.page_programmation > a
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Bulle"
      - name: country
        value: Switzerland
      - name: "location"
        value: "Ebullition"
      - name: "sourceUrl"
        value: "https://ebull.ch/fr"
      - name: title
        type: text
        location:
          - selector: div.eventListElement > div > p.artiste
            all_nodes: true
            separator: ", "
      - name: url
        type: url
        location:
          - attr: href
      - name: date
        type: date
        on_subpage: url
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: p.date
            layout:
              - "Mon. 02.01.06"
        date_location: Europe/Berlin
        date_language: fr_FR
      - name: style
        type: text
        on_subpage: url
        location:
          - selector: p.type
        can_be_empty: true
        # this should allow me to reuse the same config for mobilisons.ch
        transform:
          - type: regex-replace
            regex: theatre
            replace: THEATRE
          - type: regex-replace
            regex: party
            replace: PARTY
          - type: regex-replace
            regex: movie, concert
            replace: MUSIC
          - type: regex-replace
            regex: concert
            replace: MUSIC
          - type: regex-replace
            regex: misc\.
            replace: GAMES
          - type: regex-replace
            regex: cinéma
            replace: FILM_MEDIA
    # filters:
    #   # we'll reverse this on mobilisons.ch, to avoid duplicate
    #   - field: style
    #     exp: MUSIC
    #     match: true
