scrapers:
  - name: NewTheatreCardiff
    url: https://trafalgartickets.com/new-theatre-cardiff/en-GB/whats-on
    item: a.flex.flex-col.focus\:outline-none.focus\:ring-2.focus\:ring-offset-1.focus\:ring-offset-white.group.lg\:max-w-sm.overflow-visible.relative.rounded.size-full.text-left
    render_js: true
    interaction:
      # cookie banner
      - type: click
        selector: button#onetrust-reject-all-handler
        count: 1
        delay: 1000
      # load more events
      - type: click
        selector: span#main-content > div > div.container > div.flex > button
        count: 7
        delay: 2000
    fields:
      - name: "location"
        value: The New Theatre
      - name: "city"
        value: "Cardiff"
      - name: "sourceUrl"
        value: "https://trafalgartickets.com/new-theatre-cardiff"
      - name: date
        type: date
        on_subpage: url
        components:
          - covers:
              day: true
              month: true
              time: true
              year: true
            location:
              selector: script[type="application/ld+json"]
              json_selector: "//startDate"
            layout: ["2006-01-02T15:04:05.000Z"]
      - name: comment
        type: text
        on_subpage: url
        location:
          - selector: '#main-content > div.container > div > div > div > div[data-track="true"]'
            entire_subtree: true
        can_be_empty: true
      - name: title
        type: text
        location:
          - selector: div.flex.flex-col.gap-3.lg\:h-full.relative > div.flex.flex-col > h3.font-bold.lg\:font-semibold.lg\:text-display-sm.text-mobile-body.text-navy-200.text-navy-200
      - name: type
        type: text
        location:
          - selector: div.flex.flex-col.gap-3.lg\:h-full.relative > div.flex.flex-col > span.font-medium.text-navy-100.text-xs.uppercase
        transform:
          - type: regex-replace
            regex: "^Music$"
            replace: concert
        can_be_empty: true
      - name: url
        type: url
        location:
          - attr: href
      - name: imageUrl
        type: url
        location:
          selector: img
          attr: src
    filters:
      - field: "type"
        exp: concert
        match: true
      - field: "type"
        exp: Musical
        match: true
      - field: "type"
        exp: Comedy
        match: true
      - field: "type"
        exp: "Classical & Opera"
        match: true
