scrapers:
  - name: EmptyBottle
    url: https://www.emptybottle.com
    item: div.Site.loaded > div.Site-inner.Site-inner--index > div.Content-outer > main.Index > section.Index-page > div.Index-page-content > div.sqs-layout.sqs-grid-12.columns-12 > div.row.sqs-row > div.col.sqs-col-12.span-12 > div.row.sqs-row > div.col.sqs-col-9.span-9 > div.sqs-block.code-block.sqs-block-code > div.sqs-block-content > div.empty-bottle > div.eb-item
    fields:
      - name: location
        value: The Empty Bottle
      - name: city
        value: Chicago
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://www.emptybottle.com"
      - name: "url"
        value: "https://www.emptybottle.com"
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
            location:
              selector: div.content-front > div.show-details > div.date-time-outer > div.date
            layout: ["Mon January 2"]
          - covers:
              time: true
            location:
              selector: div.content-front > div.show-details > div.date-time-outer > div.start-time
            layout: ["3:04PM"]
        date_location: America/Chicago
        guess_year: true
      - name: title
        type: text
        location:
          selector: div.content-front > div.show-details > div.title
      - name: comment
        type: text
        location:
          selector: div.content-back > div.item-description
        can_be_empty: true
    fetcher:
      type: dynamic

  - name: Hideout
    url: https://hideoutchicago.com/events/
    item: div.eventWrapper
    fields:
      - name: location
        value: The Hideout
      - name: city
        value: Chicago
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://hideoutchicago.com/events/"
      - name: url
        type: url
        location:
          selector: a.url
          attr: href
      - name: title
        type: text
        location:
          selector: a.url
          attr: title
      - name: comment
        type: text
        location:
          selector: div.singleEventDescription
          entire_subtree: true
          max_length: 200
        on_subpage: url
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.singleEventDate
            layout: ["Mon, Jan 2, 2006", "Mon, January 2, 2006"]
          - covers:
              time: true
            location:
              selector: div.eventDoorStartDate
              entire_subtree: true
              regex_extract:
                exp: "Show: [0-9:]+pm"
            layout: ["Show: 3pm", "Show: 3:04pm"]
        date_location: America/Chicago

  - name: SchubasTavern
    url: https://lh-st.com/
    item: body.home.page-template-default.page.page-id-78 > div.container.my-5 > div.row.row-cols-1.row-cols-md-2.row-cols-lg-3.g-4.tessera-card-deck > div.col > div.card.mb-3.h-100.tessera-show-card
    fields:
      - name: "city"
        value: "Chicago"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://lh-st.com/"
      - name: url
        type: url
        location:
          selector: div.card-header > div.tessera-has-inventory > a
          attr: href
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
            location:
              selector: div.card-body.d-flex.flex-column > div.tessera-date > span.date
            layout: ["Jan 2"]
          - covers:
              time: true
            location:
              selector: div.card-body.d-flex.flex-column > div.row.mt-auto.align-items-end.tessera-buttons-container > div.col-md-6.show-details.text-end.p-0 > div.tessera-showTime > b
            layout: ["3:04PM"]
        date_location: "America/Chicago"
        date_language: "en_US"
        guess_year: true
      - name: title
        type: text
        location:
          - selector: div.card-body.d-flex.flex-column > a > h4.card-title
          - selector: div.card-body.d-flex.flex-column > div.tessera-additionalArtists
        separator: ", "
      - name: comment
        type: text
        location:
          selector: div.card-body.d-flex.flex-column > div.tessera-primaryBandAppend
        can_be_empty: true
      - name: location
        type: text
        location:
          selector: div.card-footer.text-start.align-items-center > span.tessera-venue
          child_index: 1

  - name: Subterranean
    url: https://www.subt.net/calendar/
    item: main > div.container > div > div > div.tw-plugin-calendar-list > div.tw-cal-event > div.row
    fields:
      - name: location
        value: Subterranean
      - name: city
        value: Chicago
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.subt.net/calendar/
      - name: title
        type: text
        location:
          - selector: div.columns.ten > div.tw-name:nth-child(2) > a
      - name: url
        type: url
        location:
          - selector: div.columns.ten > div.tw-name:nth-child(2) > a
            attr: href
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.columns.two:nth-child(3) > a.tw-cal-button > span.tw-event-time-complete:nth-child(2) > span.tw-event-time
            layout:
              - 15:04 pm
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.tw-date:nth-child(2) > span.tw-event-date-complete:nth-child(2) > span.tw-event-date
            layout:
              - January 2, 2006
        date_location: America/Chicago
        date_language: en_US

  - name: BeatKitchen
    url: https://www.beatkitchen.com/calendar/
    item: main > div.container > div > div > div.tw-plugin-calendar-list > div.tw-cal-event > div.row
    fields:
      - name: location
        value: Beat Kitchen
      - name: city
        value: Chicago
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.beatkitchen.com/calendar/
      - name: title
        type: text
        location:
          - selector: div.columns.ten > div.tw-name:nth-child(2) > a
      - name: url
        type: url
        location:
          - selector: div.columns.ten > div.tw-name:nth-child(2) > a
            attr: href
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.columns.two:nth-child(3) > a.tw-cal-button > span.tw-event-time-complete:nth-child(2) > span.tw-event-time
            layout:
              - 15:04 pm
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.tw-date:nth-child(2) > span.tw-event-date-complete:nth-child(2) > span.tw-event-date
            layout:
              - January 2, 2006
        date_location: America/Chicago
        date_language: en_US

  - name: Metro
    url: https://metrochicago.com/events/
    item: div.generalView > div.col-12.eventWrapper.px-0.py-4.rhpSingleEvent > div.g-0.row
    fields:
      - name: location
        value: Metro
      - name: city
        value: Chicago
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://metrochicago.com/events/
      - name: title
        type: text
        location:
          - selector: a.url > h2
      - name: url
        type: url
        location:
          - selector: a.url
            attr: href
      - name: imageUrl
        type: url
        location:
          - selector: img
            attr: src
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
            location:
              selector: div#eventDate
            layout:
              - Mon, January 2
              - Mon, Jan 2
            transform:
              - type: regex-replace
                regex: Sept
                replace: Sep
          - covers:
              time: true
            location:
              selector: div.eventDoorStartDate > span
              regex_extract:
                exp: "[0-9]{1,2}[0-9:]*[ap]{1}m"
                index: -1
            layout:
              - 15pm
              - 15:04pm
        date_location: America/Chicago
        date_language: en_US

  - name: ThaliaHall
    url: https://www.thaliahallchicago.com/shows
    item: div.thalia > div.eb-item > div.content-front > div.show-details
    fields:
      - name: location
        value: Thalia Hall
      - name: city
        value: Chicago
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.thaliahallchicago.com/shows
      - name: url
        value: https://www.thaliahallchicago.com/shows
      - name: title
        type: text
        location:
          - selector: ul.performing > li
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.date-time-outer > div.start-time:nth-child(2)
            layout:
              - "Doors: 15:04PM"
          - covers:
              day: true
              month: true
            location:
              selector: div.date-time-outer > div.date
            layout:
              - Mon January 2
        date_location: America/Chicago
        date_language: en_US
        guess_year: true
    fetcher:
      type: dynamic

  - name: SleepingVillage
    url: https://sleeping-village.com/events/
    item: div.listings-block-list__listing
    fields:
      - name: location
        value: Sleeping Village
      - name: city
        value: Chicago
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://sleeping-village.com/events/
      - name: comment
        type: text
        location:
          - selector: div.listing__description > p
      - name: title
        type: text
        location:
          - selector: div.listing__title > h3
      - name: url
        type: url
        location:
          - selector: a.listing__title-link
            attr: href
      - name: imageUrl
        type: url
        location:
          - selector: div.listing__image img
            attr: src
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              time: true
            location:
              selector: p.listing-date-time > span.listing-date-time__date > span
            layout:
              - Mon, Jan 2 15:04PM
        date_location: America/Chicago
        date_language: en_US
        guess_year: true
    fetcher:
      type: dynamic
    paginator:
      location:
        selector: body > div:nth-child(1) > div > div:nth-child(2) > div > div > div:nth-child(4) > div > a.pagination-next.pagination-prev-next
      max_pages: 3

  # currently, 19/4/2024, no events on their website
  - name: GoldenDagger
    url: https://goldendagger.com/
    item: div.site > div.wrapper > div.container > div.row > div.col-md-9.content-area > main.site-main > article.hentry.page.post-18.status-publish.type-page > div.entry-content > div > div.tw-plugin-upcoming-event-list > div.container > div.tw-section > div.row > div.columns.six:nth-child(2)
    fields:
      - name: location
        value: Golden Dagger
      - name: city
        value: Chicago
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://goldendagger.com/
      - name: title
        type: text
        location:
          - selector: div.tw-name > a
      - name: url
        type: url
        location:
          - selector: div.tw-name > a
            attr: href
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.tw-date-time:nth-child(3) > div.tw-date-time > span.tw-event-time-complete:nth-child(2) > span.tw-event-time
            layout:
              - 15:04 pm
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.tw-date-time:nth-child(3) > span.tw-event-date-complete:nth-child(2) > span.tw-event-date
            layout:
              - January 2, 2006
        date_location: America/Chicago
        date_language: en_US
    paginator:
      location:
        selector: div.entry-content > div.tw-paginate > span > span.next > a
