scrapers:
  - name: Luxor
    url: https://www.luxor-koeln.de/programm/
    item: body.page-template.page-template-page-events.page-template-page-events-php.page.page-id-26.wp-embed-responsive.preload > main.content > article.article.post-26.page.type-page.status-publish.hentry > section.events-overview.alignwide > div.events-overview__listing > article
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Cologne"
      - name: "country"
        value: "Germany"
      - name: "location"
        value: "Luxor"
      - name: "sourceUrl"
        value: "https://www.luxor-koeln.de/programm/"
      - name: eventType
        type: text
        location:
          selector: div.event-sneak-peek__content > span.event-sneak-peek__subtitle > a
        hide: true
        can_be_empty: true
      - name: title
        location:
          selector: div.event-sneak-peek__content > h3.event-sneak-peek__title > a
      - name: url
        type: url
        location:
          selector: a.event-sneak-peek__btn
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.event-sneak-peek__meta > div.event-sneak-peek__date
            layout: ["Mon 02.01.2006"]
          - covers:
              time: true
            location:
              selector: div.event-sneak-peek__meta > div.event-sneak-peek__time
            layout: ["15:04 Uhr"]
        date_location: "Europe/Berlin"
        date_language: "de_DE"
    filters:
      - field: "eventType"
        exp: "Konzerte & Events"
        match: true
      - field: "title"
        exp: ".*ABGESAGT.*"
        match: false

  - name: Kantine
    url: https://kantine.com/eventliste/
    item: div.row > div.col-6.col-md-6 > div.decm-events-details
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Cologne"
      - name: "country"
        value: "Germany"
      - name: "sourceUrl"
        value: https://kantine.com/eventliste/
      - name: url
        type: url
        location:
          - selector: h4.entry-title.summary > a
            attr: href
      - name: title
        type: text
        location:
          - selector: h4.entry-title.summary > a
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.decm-show-detail-center > span.decm-show-data-display-block.duration.ecs-eventDate.eventDate-ecs-icon.time > span.decm_date
            layout:
              - 2.1.2006
          - covers:
              time: true
            location:
              selector: div.decm-show-detail-center > span.decm-show-data-display-block.duration.ecs-eventTime.eventTime-ecs-icon.time > span.decm_time
              regex_extract:
                exp: "[0-9]{2}:[0-9]{2}"
            layout:
              - "15:04"
        date_location: CET
      - name: location
        type: text
        location:
          - selector: div.decm-show-detail-center > span.decm-show-data-display-block.duration.ecs-eventTime.eventTime-ecs-icon.time > span.decm-show-data-display-block.duration.ecs-venue.venue.venue-ecs-icon > span.decm_venue
            regex_extract:
              exp: "[a-zA-Z]+( [a-zA-Z]+)?"
    render_js: true
    interaction:
      type: click
      selector: div.et_pb_section.et_pb_section_1.et_section_regular > div > div > div > div > div > div > div.event_ajax_load.et_pb_button_wrapper > a
      count: 3
      delay: 3000
    filters:
      - field: "title"
        exp: ".*(?i)(abgesagt).*"
        match: false
      - field: title
        exp: ".*Party.*"
        match: false
