scrapers:
  - name: BadBonn
    url: https://club.badbonn.ch/program
    item: div.program-row
    fields:
      - name: "location"
        value: "Bad Bonn"
      - name: "city"
        value: "Düdingen"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://club.badbonn.ch/program
      - name: "url"
        type: url
        location:
          selector: div.program-row > div.program-bands > a
          attr: href
      - name: "title"
        type: text
        location:
          selector: div.program-row > div.program-bands > a
      - name: "date"
        type: date
        components:
          - covers:
              month: true
            location:
              selector: div.program-row > div.program-month
            layout: ["Jan"]
          - covers:
              year: true
            location:
              selector: div.program-row > div.program-year
            layout: ["2006"]
          - covers:
              time: true
            location:
              selector: div.program-row > div.program-time > a
            layout: ["15:04"]
          - covers:
              day: true
            location:
              selector: div.program-row > div.program-day > a
            layout: ["2"]
        date_location: "Europe/Berlin"
        date_language: "en_US"
