scrapers:
  - name: FriSon
    url: https://fri-son.ch/fr/programme
    item: article.node
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Fribourg"
      - name: country
        value: Switzerland
      - name: "location"
        value: "Fri-Son"
      - name: "sourceUrl"
        value: https://fri-son.ch/fr/programme
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: time
              attr: datetime
            layout: ["2006-01-02T15:04:05Z"]
          - covers:
              time: true
            location:
              selector: div.field.field--name-field-time-doors.field--type-time.field--label-hidden.field__item
            layout: ["15:04"]
        date_location: CET
        date_language: fr_FR
      - name: genre
        type: text
        location:
          - selector: div.genre-wrapper > div.field > div.field__item > span
            all_nodes: true
            separator: ", "
        can_be_empty: true
      - name: title
        type: text
        location:
          - selector: div.performer
            all_nodes: true
            separator: ", "
      - name: url
        type: url
        location:
          selector: article.node > a
          attr: href
      - name: imageUrl
        type: url
        location:
          selector: picture > img
          attr: src
    paginator:
      location:
        selector: li.pager__item > a

  - name: LaSpirale
    url: https://laspirale.ch/programme/
    item: div.prog_concert
    fields:
      - name: "location"
        value: "La Spirale"
      - name: "city"
        value: "Fribourg"
      - name: "country"
        value: "Switzerland"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://laspirale.ch/programme/"
      - name: title
        type: text
        location:
          - selector: div.droite > h2
      - name: imageUrl
        type: url
        location:
          - selector: img
            attr: src
      - name: url
        type: url
        location:
          - selector: a.masterlink
            attr: href
      - name: comment
        type: text
        on_subpage: url
        location:
          - selector: div.gauche > p
            all_nodes: true
        can_be_empty: true
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.droite > p
              regex_extract:
                exp: "^[A-z]+ [0-9]{1,2}(er)? [A-zé]+ [0-9]{4}"
            layout: ["Monday 2 January 2006", "Monday 2er January 2006"]
          - covers:
              time: true
            location:
              selector: div.droite > p
              regex_extract:
                exp: "[0-9]{2}h[0-9]{0,2}"
            layout: ["15h04", "15h"]
        date_language: fr_FR
        date_location: CET

  - name: NouveauMonde
    url: https://www.nouveaumonde.ch/agenda/
    item: body > div > div.appScroll > div.content.scrollable > div.flexColumn.gap.spaceBottom > section.appToFilter.column6.flexRow.gap > a.poster.size50
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Fribourg"
      - name: country
        value: Switzerland
      - name: "location"
        value: "Nouveau Monde"
      - name: "sourceUrl"
        value: https://www.nouveaumonde.ch/agenda/
      - name: title
        type: text
        location:
          - selector: div:nth-child(3) > h4
      - name: genre
        type: text
        location:
          - selector: div:nth-child(3) > ul.flexRow > li.plate.plateMedium
      - name: date
        type: date
        components:
          - covers:
              year: true
              month: true
              day: true
            location:
              selector: h3.date
            layout: ["02.01.2006"]
          - covers:
              time: true
            location:
              selector: h4.dateHM
            layout: ["15h04"]
        date_location: CET
        date_language: fr_FR
      - name: url
        type: url
        location:
          - attr: href
      - name: imageUrl
        type: url
        location:
          - selector: div:nth-child(1) > img
            attr: src
    filters:
      - field: genre
        exp: "rct"
        match: false
      - field: genre
        exp: "caf"
        match: false
      - field: genre
        exp: "fml"
        match: false
      - field: genre
        exp: "spt"
        match: false
