scrapers:
  - name: Fabrik
    url: https://fabrik.de/programm
    item: body > div.page > article > div.programm_termin > div.programm_termin_lh
    fields:
      - name: "location"
        value: "Fabrik"
      - name: "city"
        value: "Hamburg"
      - name: "country"
        value: "Germany"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://fabrik.de/programm"
      - name: url
        type: url
        location:
          selector: div.programm_termin_lh_datum > a.tdcn
          attr: href
      - name: comment
        type: text
        location:
          selector: a.tdcn > div.programm_termin_untertitel
        can_be_empty: true
      - name: title
        type: text
        location:
          selector: a.tdcn > div.programm_termin_titel
      - name: category
        location:
          selector: div.programm_termin_lh_vorne > div.programm_kategorie
        can_be_empty: true
        hide: true
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.programm_termin_lh_datum > a.tdcn
              child_index: 1
            layout: ["2.1.2006"]
          - covers:
              time: true
            location:
              selector: div.programm_termin_infos
              child_index: 2
            layout: ["Beginn: 15:04 Uhr"]
        date_location: "Europe/Berlin"
    filters:
      - field: category
        exp: Konzert
        match: true

  - name: Knust
    url: https://www.knusthamburg.de/programm/
    item: div.type-konzert
    fields:
      - name: "location"
        value: "Knust"
      - name: "city"
        value: "Hamburg"
      - name: "country"
        value: "Germany"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.knusthamburg.de/programm/
      - name: "date"
        type: "date"
        components:
          - covers:
              day: true
            location:
              selector: div.date > span.day
            layout: ["02"]
          - covers:
              month: true
            location:
              selector: div.date > span.month
            layout: ["Jan"]
          - covers:
              year: true
            location:
              selector: div.date > span.year
            layout: ["2006"]
          - covers:
              time: true
            location:
              selector: ul > li.event > div.event-text > span.location
              regex_extract:
                exp: "[0-9]{2}:[0-9]{2}"
            layout: [15:04]
        date_location: "Europe/Berlin"
      - name: "url"
        type: url
        location:
          selector: ul > li.event > div.event-text > h3 > a
          attr: href
      - name: "title"
        type: text
        location:
          selector: ul > li.event > div.event-text > h3 > a
      - name: "comment"
        type: text
        location:
          selector: ul > li.event > div.event-text > span.subtitle
        can_be_empty: true
      - name: "room"
        type: text
        location:
          selector: ul > li.event > div.event-text > span.location
          regex_extract:
            exp: "[^|]*"
            index: 0

  - name: Hafenklang
    url: https://www.hafenklang.com/programm/konzerte/
    item: body.page.page-child.page-id-77.page-template-default.parent-pageid-17 > div > div.section-inner.site > main.site-main > article.hentry.page.post-77.status-publish.type-page > div.entry-content > article.cp-event.cp-event-
    fields:
      - name: "location"
        value: "Hafenklang"
      - name: "city"
        value: "Hamburg"
      - name: "country"
        value: "Germany"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.hafenklang.com/programm/konzerte/
      - name: "url"
        type: url
        location:
          selector: div.cp-title-mobile.mobile-only > h2.cp-title > a
          attr: href
      - name: "title"
        type: text
        location:
          selector: div.cp-title-mobile.mobile-only > h2.cp-title > a
      - name: "comment"
        type: text
        location:
          selector: div.cp-title-mobile.mobile-only > h2.cp-title > a > span.cp-sub-title
        can_be_empty: true
      - name: "date"
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.col.col-12.col-md-4.cp-meta > p.cp-date
              regex_extract:
                exp: "[0-9]{2}.[0-9]{2}.[0-9]{2}"
            layout: ["02.01.06"]
          - covers:
              time: true
            location:
              selector: div.col.col-12.col-md-4.cp-meta > p.cp-times > span.cp-start
              regex_extract:
                exp: "[0-9]{2}:[0-9]{2}"
            layout: ["15:04"]
        date_location: "Europe/Berlin"
        date_language: "de_DE"
      - name: "room"
        type: text
        location:
          selector: div.col.col-12.col-md-4.cp-meta > span.cp-room

  - name: Uebelundgefaehrlich
    url: https://www.uebelundgefaehrlich.com/
    item: body > div > main.grid-container > ul.event > li.konzert > a.history
    fields:
      - name: "location"
        value: "Uebel & Gefährlich"
      - name: "city"
        value: "Hamburg"
      - name: "country"
        value: "Germany"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.uebelundgefaehrlich.com/
      - name: url
        type: url
        location:
          - attr: href
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.grid-70.grid-parent.mobile-grid-70.tablet-grid-70 > time
            layout:
              - Monday, den 2. January 2006
          - covers:
              time: true
            location:
              selector: div.grid-70.grid-parent.mobile-grid-70.tablet-grid-70
              child_index: 4
              regex_extract:
                exp: "[0-9]{2}:[0-9]{2}"
                index: 1
            layout: ["15:04"]
        date_location: CET
        date_language: de_DE
      - name: title
        type: text
        location:
          - selector: div.grid-70.grid-parent.mobile-grid-70.tablet-grid-70 > h1
