scrapers:
  - name: Taeubchenthal
    url: https://www.taeubchenthal.com/programm
    item: body > div > main > div.block.mod_article.mod_article--row > div.row > div.block.mod_eventlist.mod_eventlist--default.row > div.cal_1.col.col-md-4.col-sm-6.event.event--list.layout_list.upcoming > div.inside
    fields:
      - name: location
        value: Täubchenthal
      - name: city
        value: Leipzig
      - name: type
        value: concert
      - name: sourceUrl
        value: https://www.taeubchenthal.com/programm
      - name: url
        type: url
        location:
          selector: h2 > a
          attr: href
      - name: title
        type: text
        location:
          selector: h2 > a
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
              time: true
            location:
              selector: p.time > time
              attr: datetime
            layout: ["2006-01-02T15:04:05-07:00"]

  - name: Werk2
    url: https://www.werk-2.de/
    item: body.programm.aktuell > div > div > div > div > div#vorschaukasten > ul > li:not(.monat)
    fields:
      - name: location
        value: Werk 2
      - name: city
        value: Leipzig
      - name: type
        value: concert
      - name: sourceUrl
        value: https://www.werk-2.de/
      - name: url
        type: url
        location:
          - selector: p.veranstaltung > span > a
            attr: href
      - name: title
        type: text
        location:
          - selector: p.veranstaltung > span > a
      - name: category
        on_subpage: url
        location:
          selector: div.vak_info > div.ueber_container > p.typen > font > b
        hide: true
      - name: date
        type: date
        on_subpage: url
        components:
          - covers:
              month: true
            location:
              selector: div.vak_datum_links > div.monat
            layout:
              - January
          - covers:
              day: true
            location:
              selector: div.vak_datum_links > div.tag
            layout:
              - 2
          - covers:
              time: true
            location:
              selector: div.vak_info > div.text_container_ohne_bild > p.infos
              regex_extract:
                exp: "Beginn: [0-9]{2}"
            layout:
              - "Beginn: 15"
        date_location: CET
        date_language: de_DE
        guess_year: true
    filters:
      - field: category
        exp: "Lesung.*"
        match: false
      - field: category
        exp: Party
        match: false
      - field: category
        exp: Film
        match: false
      - field: category
        exp: Podiumsdiskussion
        match: false
      - field: category
        exp: "Theater.*"
        match: false
