scrapers:
  - name: Schuur
    url: https://www.schuur.ch/programm/
    item: div.viz-event-list article
    fields:
      - name: "location"
        value: "Konzerthaus Schüür"
      - name: "city"
        value: "Lucerne"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.schuur.ch/programm/
      - name: comment
        location:
          selector: span.viz-event-headline
        can_be_empty: true
      - name: title
        location:
          selector: span.viz-event-name
      - name: url
        type: url
        location:
          selector: h3 > a.viz-event-box-details-link
          attr: href
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
              time: true
            location:
              selector: div.viz-event-date
            layout:
              - "Mon. 2. January 2006 – 15:04"
              - "Mon. 2. Jan. 2006 – 15:04"
        date_location: "Europe/Berlin"
        date_language: "de_DE"

  - name: Bar59
    url: https://www.bar59.ch/
    item: body > div.container > div > div.contentBlock.events > div.day
    fields:
      - name: "location"
        value: "Bar 59"
      - name: "city"
        value: "Lucerne"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.bar59.ch/
      - name: "url"
        value: https://www.bar59.ch/
      - name: title
        type: text
        location:
          - selector: div.event:nth-child(2) > h3.collapsed > span
      - name: imageUrl
        type: url
        location:
          - selector: div.col-xs-12.col-md-9.col-md-pull-3.left > img
            attr: src
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.event:nth-child(2) > h3.collapsed > small
            layout:
              - "15:04"
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.daylabel > span.big
            layout:
              - Monday 2.1.2006
        date_location: CET
        date_language: de_DE
    fetcher:
      type: dynamic
      page_load_wait_ms: 5000
    paginator:
      location:
        selector: div.paginatorContainer > div > button:nth-child(3)
      max_pages: 4

  - name: Neubad
    url: https://neubad.org/veranstaltungen?f%5B0%5D=kategorie_der_veranstaltung_%3AKonzert
    item: div.view-content > div.w3-section > div.cal.item-list
    fields:
      - name: "location"
        value: Neubad
      - name: "city"
        value: "Lucerne"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://neubad.org/veranstaltungen?f%5B0%5D=kategorie_der_veranstaltung_%3AKonzert
      - name: title
        type: text
        location:
          - selector: div.vorschau > a > span.title
      - name: url
        type: url
        location:
          selector: span.field-content > div.vorschau > a
          attr: href
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.views-field.views-field-field-datum-event-3 > span.field-content
            layout:
              - "15:04"
          - covers:
              day: true
              month: true
            location:
              selector: h3
            layout:
              - Mon. 2. January
        date_location: CET
        date_language: de_DE
        guess_year: true

  - name: Jazzkantine
    url: https://www.jazzkantine.com/veranstaltungen
    item: div.eventlist.eventlist--upcoming > article.eventlist-event.eventlist-event--hasimg.eventlist-hasimg.is-loaded
    fields:
      - name: "location"
        value: Jazzkantine
      - name: "city"
        value: "Lucerne"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.jazzkantine.com/veranstaltungen
      - name: comment
        type: text
        can_be_empty: true
        location:
          - selector: div.eventlist-column-info > div.eventlist-description > div.columns-12.sqs-grid-12.sqs-layout > div.row.sqs-row > div.col.span-12.sqs-col-12 > div.html-block.sqs-block.sqs-block-html > div.sqs-block-content > div.sqs-html-content > p
            entire_subtree: true
      - name: title
        type: text
        location:
          - selector: div.eventlist-column-info > h1.eventlist-title > a.eventlist-title-link
      - name: url
        type: url
        location:
          - selector: div.eventlist-column-info > h1.eventlist-title > a.eventlist-title-link
            attr: href
      - name: imageUrl
        type: url
        location:
          - selector: a.content-fill.eventlist-column-thumbnail > img
            attr: src
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.eventlist-column-info > ul.event-meta.eventlist-meta > li.event-meta-item.eventlist-meta-item.eventlist-meta-time > span.event-time-localized > time.event-time-localized-start
            layout:
              - "15:04"
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.eventlist-column-info > ul.event-meta.eventlist-meta > li.event-meta-item.eventlist-meta-date.eventlist-meta-item > time.event-date
            layout:
              - Monday, 2. January 2006
        date_location: CET
        date_language: de_DE
    fetcher:
      type: dynamic
      page_load_wait_ms: 2000
