scrapers:
  - name: Schuur
    url: https://www.schuur.ch/programm/
    item: div.viz-event-list article
    fields:
      - name: "location"
        value: "Konzerthaus Schüür"
      - name: "city"
        value: "Lucerne"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.schuur.ch/programm/
      - name: comment
        location:
          selector: span.viz-event-headline
        can_be_empty: true
      - name: title
        location:
          selector: span.viz-event-name
      - name: url
        type: url
        location:
          selector: h3 > a.viz-event-box-details-link
          attr: href
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
              time: true
            location:
              selector: div.viz-event-date
            layout: ["Mon. 2. January 2006 – 15:04"]
        date_location: "Europe/Berlin"
        date_language: "de_DE"
