scrapers:
  - name: MercatoSonato
    url: https://www.senzaspine.org/centro-culturale#anchor-eventi-mercato
    item: div.eventi-section > div.collection-list-wrapper-9.w-dyn-list > div.collection-list-evenit-scuola.w-dyn-items > div.collection-item-3.w-dyn-item
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Milan"
      - name: country
        value: Italy
      - name: "location"
        value: "Mercato Sonato"
      - name: "sourceUrl"
        value: https://www.senzaspine.org/centro-culturale#anchor-eventi-mercato
      - name: comment
        type: text
        location:
          - selector: div.eventi-box-content > div.titolo-descrizione > div.eventi-box-text-block.eventi-box-text-block-descrizione-orchestra
      - name: title
        type: text
        location:
          - selector: div.eventi-box-content > div.titolo-descrizione > h3.eventi-orchestra-title.h3-styles
      - name: url
        type: url
        location:
          - selector: a.eventi-box-image.w-inline-block
            attr: href
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.eventi-box-content > div.data-ora-container > div.eventi-box-text-block.eventi-box-text-block-data-ora > div:nth-child(5)
            layout:
              - "15:04"
          - covers:
              year: true
            location:
              selector: div.eventi-box-content > div.data-ora-container > div.eventi-box-text-block.eventi-box-text-block-data-ora > div.dateclass:nth-child(3)
            layout:
              - "2006"
          - covers:
              day: true
            location:
              selector: div.eventi-box-content > div.data-ora-container > div.eventi-box-text-block.eventi-box-text-block-data-ora > div.dateclass
            layout:
              - "2"
          - covers:
              month: true
            location:
              selector: div.eventi-box-content > div.data-ora-container > div.eventi-box-text-block.eventi-box-text-block-data-ora > div.dateclass:nth-child(2)
            layout:
              - January
        date_location: CET
    paginator:
      location:
        selector: "div.pagination > a.w-pagination-next"
      max_pages: 6
