scrapers:
  - name: PontRouge
    url: https://www.pontrouge.ch/
    item: .Zc7IjY
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Monthey"
      - name: country
        value: Switzerland
      - name: "location"
        value: "Pont Rouge"
      - name: "sourceUrl"
        value: "https://www.pontrouge.ch/"
      - name: "url"
        value: "https://www.pontrouge.ch/"
      - name: date
        type: date
        components:
          - covers:
              day: true
            location:
              selector: div > div > div > div > div > div > div > p:nth-child(1) > span
              regex_extract:
                exp: "[0-9]{2}"
            layout:
              - "02"
          - covers:
              month: true
            location:
              selector: div > div > div > div > div > div > div > p:nth-child(2) > span
            transform:
              - type: regex-replace
                regex: FEV
                replace: Févr
            layout:
              - "JAN."
              - "Jan."
              - "Jan"
              - "JAN"
          - covers:
              year: true
            location:
              selector: div > div > div > div > div > div > div > p:nth-child(3) > span
            layout:
              - "2006"
          - covers:
              time: true
            location:
              default: "20:00"
            layout: ["15:04"]
        date_location: Europe/Berlin
        date_language: fr_FR
      - name: title
        type: text
        location:
          - selector: div > div:nth-child(2) > h4
            entire_subtree: true
