scrapers:
  - name: LaCigale
    url: "https://lacigale.fr/en/lineup/"
    item: ul.artiste-event.artiste-event--prog > li.artiste-event__item > a.artiste-event__link
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Paris"
      - name: "location"
        value: "La Cigale"
      - name: "sourceUrl"
        value: "https://lacigale.fr/en/lineup/"
      - name: title
        type: text
        location:
          - selector: div.artiste-event__content:nth-child(2) > p.artiste-event__title
      - name: comment
        type: text
        location:
          - selector: div.artiste-event__content:nth-child(2) > ul.list-date.list-date--no-margin > li.list-date__item:nth-child(2) > p
        can_be_empty: true
      - name: url
        type: url
        location:
          - attr: href
      - name: status
        location:
          - selector: div.artiste-event__content-img > p
        can_be_empty: true
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.artiste-event__content:nth-child(2) > ul.list-date.list-date--no-margin:nth-child(3) > li.list-date__item:nth-child(2) > p
            layout:
              - "15:04"
          - covers:
              day: true
              month: true
            location:
              selector: div.artiste-event__content:nth-child(2) > ul.list-date.list-date--no-margin:nth-child(3) > li.list-date__item > p
            layout:
              - Mon 2 Jan
        date_location: CET
        date_language: en_US
        guess_year: true
    filters:
      - field: "status"
        exp: CANCELED
        match: false
      - field: "status"
        exp: POSTPONED
        match: false

  - name: NewMorning
    url: https://www.newmorning.com/programmation
    item: div.container.me-xl-0.mw-100.pe-2.pe-xl-0.ps-2 > section.d-sm-none.mt-3 > a
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Paris"
      - name: "location"
        value: "New Morning"
      - name: "sourceUrl"
        value: "https://www.newmorning.com/programmation"
      - name: comment
        on_subpage: url
        location:
          - selector: "#main > div.me-0.row > div.col-12.col-lg-10.pe-0 > main > section > div > section.pb-md-2.text-center.text-md-start.text-secondary > div > div > div.col-md-8 > p.fst-italic.text-center.text-light.text-md-start"
          - selector: "#event-info > div.col-lg-8.col-md-8.col-xl-8.pb-3.pe-md-3.pt-md-3.text-center.text-md-start > div:nth-child(2)"
            entire_subtree: true
        separator: "\n"
        can_be_empty: true
      - name: title
        type: text
        location:
          - selector: div.align-items-center.bg-white.mb-3.me-0.ms-0.no-gutters.p-2.rounded.row.shadow.text-body > div.col-11.m-0.pt-0 > div.no-gutters.row:nth-child(2) > div.col-7.ml-2.ms-2.p-0 > h6.card-title.fs-6.mb-1
      - name: imageUrl
        type: url
        location:
          - selector: div.align-items-center.bg-white.mb-3.me-0.ms-0.no-gutters.p-2.rounded.row.shadow.text-body > div.col-11.m-0.pt-0 > div.no-gutters.row:nth-child(2) > div.col-4.p-0 > div.carousel.carousel-fade.slide > div.carousel-inner > div.active.carousel-item > img.img-fluid.w-100
            attr: src
      - name: url
        type: url
        location:
          - attr: href
      - name: date
        type: date
        on_subpage: url
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: "#main > div.me-0.row > div.col-12.col-lg-10.pe-0 > main > section > div > section.bg-opacity-75.bg-white.border.mb-3.pe-2.pe-sm-4.ps-2.ps-sm-4.pt-2.pt-sm-3.text-secondary > header > h1"
            layout:
              - Monday 2/1/2006
          - covers:
              time: true
            location:
              selector: "#main > div.me-0.row > div.col-12.col-lg-10.pe-0 > main > section > div > section.bg-opacity-75.bg-white.border.mb-3.pe-2.pe-sm-4.ps-2.ps-sm-4.pt-2.pt-sm-3.text-secondary > header > p:nth-child(3)"
              regex_extract:
                exp: "[0-9]{2}h[0-9]{2}"
            layout:
              - 15h04
        date_location: CET
        date_language: fr_FR

  - name: LeZenith
    url: https://le-zenith.com/program
    item: div.app-program__items.js-shows-list > div.card-show
    fields:
      - name: "type"
        value: "concert"
      - name: "city"
        value: "Paris"
      - name: "location"
        value: "Le Zenith"
      - name: "sourceUrl"
        value: "https://le-zenith.com/program"
      - name: url
        type: url
        location:
          - selector: a.button.button--bg-white-c-sky-blue.card-show__button
            attr: href
      - name: imageUrl
        type: url
        location:
          - selector: div.card-show__img > img
            attr: src
      - name: title
        type: text
        location:
          - selector: div.card-show__artist
      - name: date
        type: date
        on_subpage: url
        components:
          - covers:
              day: true
              month: true
            location:
              selector: body > div.page__content > div.app-event > section.app-event__informations > div.app-event__informations-dates > div > div:nth-child(2) > div:nth-child(1) > div
              entire_subtree: true
              regex_extract:
                exp: "[0-9]{2} [a-zèéà]+"
            layout: ["2 Jan"]
          - covers:
              year: true
            location:
              selector: body > div.page__content > div.app-event > section.app-event__informations > div.app-event__informations-dates > div > div:nth-child(2) > div:nth-child(1) > div
              entire_subtree: true
              regex_extract:
                exp: "[0-9]{4}"
            layout: ["2006"]
          - covers:
              time: true
            location:
              selector: body > div.page__content > div.app-event > section.app-event__informations > div.app-event__informations-dates > div > div:nth-child(2) > div:nth-child(1) > div
              entire_subtree: true
              regex_extract:
                exp: "[0-9]{2}:[0-9]{2}"
            layout: ["15:04"]
        date_location: CET
        date_language: fr_FR
