scrapers:
  - name: TheCatalyst
    url: "https://catalystclub.com/events/"
    item: ".eventWrapper"
    fields:
      - name: "location"
        value: "The Catalyst"
      - name: "city"
        value: "Santa Cruz"
      - name: country
        value: United States
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://catalystclub.com/events/"
      - name: "title"
        location:
          selector: "#eventTitle h2"
      - name: "url"
        type: "url"
        location:
          selector: "#eventTitle"
      - name: "date"
        type: "date"
        on_subpage: "url"
        components:
          - covers:
              day: true
              month: true
            location:
              selector: ".EventsDateBox span.eventStDate"
            layout: ["Monday, January 02"]
          - covers:
              time: true
            location:
              selector: ".eventDoorStartDate span"
              regex_extract:
                exp: "[0-9]{1}(:[0-9]{2})?pm"
                index: 1
            layout: ["3pm", "3:04pm"]
        date_location: "America/Los_Angeles"
        date_language: "en_US"
        guess_year: true
