scrapers:
  - name: BoutDuMonde
    url: https://www.leboutdumonde.ch/programme/
    item: ul.events > li
    fields:
      # static
      - name: location
        value: "Le Bout Du Monde"
      - name: city
        value: Vevey
      - name: country
        value: Switzerland
      - name: "sourceUrl"
        value: "https://www.leboutdumonde.ch"
      - name: type
        value: concert
      # dynamic
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.event_header > time
              attr: datetime # unfortunately the time component is not correct. It's always 23:59:59+00:00
              regex_extract:
                exp: "[0-9]{4}(-[0-9]{2}){2}"
            layout: ["2006-01-02"]
          - covers:
              time: true
            location:
              selector: span.hours
            layout: ["15h04", "15h"]
        date_location: "Europe/Berlin"
        date_language: fr_FR
      - name: title
        type: text
        location:
          selector: h2
          entire_subtree: true
      - name: comment
        type: text
        location:
          selector: p > a.notInline
      - name: url
        type: url
        location:
          selector: a.more
          attr: href
      - name: imageUrl
        type: url
        location:
          selector: img
          attr: src
    filters:
      - field: title
        exp: (?i)(BRUNCH)
        match: false

    # I guess there was an eventType field in this config once?
    #   - field: "eventType"
    #     exp: "Jeux"
    #     match: false

  - name: CafeLitteraire
    url: https://lecafelitteraire.ch/culture/
    item: body.culture > div.site > main.site-main > article.is_page.culture.is_parent > div.entry-content > div.wp-block-getwid-section > div.wp-block-getwid-section__wrapper > div.wp-block-getwid-section__inner-wrapper > div.wp-block-getwid-section__content > div.wp-block-getwid-section__inner-content > ul.list.evenements > li
    fields:
      - name: "location"
        value: "Café Littéraire"
      - name: "city"
        value: "Vevey"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://lecafelitteraire.ch/culture/"
      - name: "url"
        value: "https://lecafelitteraire.ch/culture/"
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
            location:
              selector: p.event_date > strong.has-green-color
            layout: ["Monday 2 January"]
          - covers:
              time: true
            location:
              selector: p.event_date > span
              regex_extract:
                exp: "[0-9]{2}:[0-9]{2}"
                index: 0 # this is the default but for clarity I left it
            layout: ["15:04"]
        date_location: "CET"
        date_language: "fr_FR"
      - name: title
        type: text
        location:
          selector: h2
      - name: comment
        type: text
        location:
          selector: p:not([class])
        can_be_empty: true # this location seems to contain events without comment. We should still scrape those.
    filters:
      - field: "title"
        exp: ".*Brunch"
        match: false
      - field: "title"
        exp: ".*Saint-Valentin"
        match: false
      - field: "title"
        exp: ".*Reveillon"
        match: false

  - name: TheRockingChair
    url: https://www.rocking-chair.ch/
    item: div.event:has(.info-futur-events)
    fields:
      - name: "location"
        value: "The Rocking Chair"
      - name: city
        value: Vevey
      - name: country
        value: Switzerland
      - name: "sourceUrl"
        value: "https://www.rocking-chair.ch/"
      - name: url
        type: "url"
        location:
          selector: a.link-project
      - name: title
        type: text
        location:
          selector: span.title_event
      - name: comment
        type: text
        location:
          selector: span.info_event > p
      - name: type
        value: "concert"
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.date_event
            layout: ["2.1.2006 "]
      - name: ticketing
        location:
          selector: span.ticketing
        can_be_empty: true

  # This one is a bit hackey because events that we actually want to exclude because they're old
  # are excluded because of a differently formatted date and hence a resulting date parsing error.
  - name: VeveySpringClassics
    url: https://veveyspringclassic.ch/en/schedule/concerts-publics/
    item: div.site-main > section.pt-4.section > div.row > div.col-sm-3 > div.concert-item > a
    fields:
      - name: type
        value: concert
      - name: "sourceUrl"
        value: https://veveyspringclassic.ch/en/schedule/concerts-publics/
      - name: country
        value: Switzerland
      - name: city
        location:
          - selector: div.concert-date.transition-fast:nth-child(4)
            regex_extract:
              exp: "[A-Za-z]+"
              index: -1
      - name: location
        type: text
        location:
          - selector: div.concert-date.transition-fast:nth-child(4)
            regex_extract:
              exp: "[^,]+"
      - name: title
        type: text
        location:
          - selector: h2.concert-title.transition-fast
      - name: url
        type: url
        location:
          - attr: href
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
              time: true
            location:
              selector: div.concert-date.transition-fast:nth-child(3)
            layout:
              - Monday 2 January 2006, 15:04
        date_location: CET
        date_language: en_US
