scrapers:
  - name: Salzhaus
    url: "https://www.salzhaus.ch/de/programm.html"
    item: ".sHprogramm"
    fields:
      - name: "location"
        value: "Salzhaus"
      - name: "city"
        value: "Winterthur"
      - name: "country"
        value: "Switzerland"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: "https://www.salzhaus.ch/de/programm.html"
      - name: "title"
        location:
          selector: ".sHInfo a"
      - name: "imageUrl"
        type: url
        location:
          selector: ".sHImg > a > img"
          attr: data-src
      - name: "comment"
        location:
          selector: ".sHInfo h2"
        can_be_empty: true
      - name: "url"
        type: "url"
        location:
          selector: ".sHInfo a"
      - name: "date"
        type: "date"
        on_subpage: "url"
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: ".sHDetailRow span"
              node_index: 3
              regex_extract:
                exp: "([0-9]{1,2}\\.){2}[0-9]{4}"
                index: 0
            layout: ["02.01.2006"]
          - covers:
              time: true
            location:
              selector: ".sHDetailRow span"
              node_index: 5
              regex_extract:
                exp: "[0-9]{2}:[0-9]{2}"
            layout: ["15:04"]
        date_location: "Europe/Berlin"

  - name: Musikfestwochen
    url: https://musikfestwochen.ch/programm/programm-nach-datum/
    item: main.columns.first.large-8.medium-8 > section.programmlist-container > article.act-item.info-invisible
    fields:
      - name: "city"
        value: "Winterthur"
      - name: "country"
        value: "Switzerland"
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://musikfestwochen.ch/programm/programm-nach-datum/
      - name: comment
        type: text
        location:
          - selector: div.programm-infos > div:nth-child(7)
        can_be_empty: true
      - name: location
        type: text
        location:
          - selector: div.programm-infos > h5:nth-child(3)
      - name: url
        type: url
        location:
          - selector: div.columns.large-4.medium-6.small-12 > a
            attr: href
      - name: title
        type: text
        location:
          - selector: div.row > div.columns.large-10.medium-8 > a > h3
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
              time: true
            location:
              selector: div.act-extend.row:nth-child(2) > div:nth-child(2) > div.programm-infos > h5
            layout:
              - Monday, 2. January 2006, 15:04
        date_location: CET
    filters:
      - field: date
        exp: "> now"
        match: true
