scrapers:
  - name: Amalgame
    url: https://www.amalgameclub.ch/programme/
    item: div.grid.three-columns > div.card--event > a
    fields:
      - name: "city"
        value: "Yverdon-les-Bains"
      - name: country
        value: Switzerland
      - name: "location"
        value: "L’Amalgame"
      - name: "sourceUrl"
        value: "https://www.amalgameclub.ch/programme/"
      - name: title
        type: text
        location:
          - selector: div.card-content > h3
      - name: type
        type: text
        location:
          - selector: div.img-wrapper > div.event-type > span.type
            default: concert
        transform:
          - type: regex-replace
            regex: "CONCERT"
            replace: concert
          - type: regex-replace
            regex: "PARTY"
            replace: party
      - name: imageUrl
        type: url
        location:
          - selector: div.img-wrapper > figure > picture > img.ofi-image
            attr: src
      - name: url
        type: url
        location:
          - attr: href
      - name: genresText
        type: text
        location:
          - selector: div.card-content > div.category-wrapper > div.category
            all_nodes: true
            separator: ", "
        can_be_empty: true
      - name: comment
        type: text
        location:
          - selector: div.card-content > div.category-wrapper > div.category
            all_nodes: true
            separator: ", "
        can_be_empty: true
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: span.date
            layout:
              - 2.1.2006
          - covers:
              time: true
            location:
              default: "20:00"
            layout:
              - 15:04
        date_location: CET
    fetcher:
      type: static
