scrapers:
  - name: Galvanik
    url: https://galvanik-zug.ch/programm/
    item: table.uk-table.uk-table-hover > tbody.js-filter > tr.event
    fields:
      - name: "location"
        value: Galvanik
      - name: "city"
        value: "Zug"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://galvanik-zug.ch/programm/
      - name: comment
        type: text
        location:
          - selector: td.cat > div.category.round-button
      - name: title
        type: text
        location:
          - selector: td.artist > a.eventLink > span.title
      - name: url
        type: url
        location:
          - selector: td.artist > a.eventLink
            attr: href
      - name: imageUrl
        type: url
        on_subpage: url
        location:
          - selector: div.small-slider > div > div > ul > li > picture > img
            attr: src
      - name: date
        type: date
        on_subpage: url
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.event-infos > div > div.date-time > h2
              child_index: 0
            layout:
              - 2. Jan. 06
          - covers:
              time: true
            location:
              selector: div.event-infos > div > div.date-time > h2
              child_index: 2
            layout:
              - 15:04 Uhr
        date_language: de_DE
        date_location: CET

  - name: HidenHarlekin
    url: https://eventfrog.ch/de/events.html?searchTerm=hiden+harlekin+zug
    item: div.event-list > div.event-list__events > a.event-list__events__tile
    fields:
      - name: "location"
        value: Hidén Harlekin
      - name: "city"
        value: "Zug"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://eventfrog.ch/de/events.html?searchTerm=hiden+harlekin+zug
      - name: title
        type: text
        location:
          - selector: div.event-list__events__tile__content > div.event-list__events__tile__content__infos > span.event-list__events__tile__content__infos__title
      - name: imageUrl
        type: url
        location:
          - selector: div.event-list__events__tile__image > img
            attr: src
      - name: url
        type: url
        location:
          - attr: href
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              time: true
            location:
              selector: div.event-list__events__tile__content > div.event-list__events__tile__content__infos > span.event-list__events__tile__content__infos__time
            layout:
              - Monday, 2. January, 15:04
        date_location: CET
        date_language: de_DE
        guess_year: true

  - name: Gewuerzmuehle
    url: https://www.gewuerzmuehle.ch/programm
    item: div.collection-item.w-dyn-item > div.programmspalte.w-row
    fields:
      - name: "location"
        value: Gewürzmühle
      - name: "city"
        value: "Zug"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://www.gewuerzmuehle.ch/programm
      - name: "url"
        value: https://www.gewuerzmuehle.ch/programm
      - name: comment
        type: text
        location:
          - selector: div.column-5.w-col.w-col-8 > div.div-block-12 > div.last.list.paragraph
        can_be_emtpy: true
      - name: title
        type: text
        location:
          - selector: div.column-5.w-col.w-col-8 > h2.h2
      - name: imageUrl
        type: url
        location:
          - selector: div.square-imageholder > img.square-image
            attr: src
      - name: date
        type: date
        components:
          - covers:
              time: true
            location:
              selector: div.column-5.w-col.w-col-8 > div.div-block-12
              entire_subtree: true
              regex_extract:
                exp: "[0-9]{2}((\\.|:)[0-9]{2})? (Uhr)?"
            layout:
              - 15.04
              - 15.04 Uhr
              - 15:04
              - 15:04 Uhr
              - 15 Uhr
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.column-5.w-col.w-col-8 > div.div-block-12 > div.date > div.date-month.date-text.paragraph
            layout:
              - 2.1.2006
        date_location: CET
    filters:
      - field: comment
        exp: ".*ausstellung.*"
        match: false
      - field: comment
        exp: "(?i)(frei bewegen)"
        match: false
      - field: comment
        exp: "(?i)(theater)"
        match: false
      - field: date
        exp: < now
        match: false
