scrapers:
  - name: Galvanik
    url: https://galvanik-zug.ch/programm/
    item: table.uk-table.uk-table-hover > tbody.js-filter > tr.event
    fields:
      - name: "location"
        value: Galvanik
      - name: "city"
        value: "Zug"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://galvanik-zug.ch/programm/
      - name: comment
        type: text
        location:
          - selector: td.cat > div.category.round-button
      - name: title
        type: text
        location:
          - selector: td.artist > a.eventLink > span.title
      - name: url
        type: url
        location:
          - selector: td.artist > a.eventLink
            attr: href
      - name: imageUrl
        type: url
        on_subpage: url
        location:
          - selector: div.small-slider > div > div > ul > li > picture > img
            attr: src
      - name: date
        type: date
        on_subpage: url
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: div.event-infos > div > div.date-time > h2
              child_index: 0
            layout:
              - 2. Jan. 06
          - covers:
              time: true
            location:
              selector: div.event-infos > div > div.date-time > h2
              child_index: 2
            layout:
              - 15:04 Uhr
        date_language: de_DE
        date_location: CET

  - name: HidenHarlekin
    url: https://eventfrog.ch/de/events.html?searchTerm=hiden+harlekin+zug
    item: div.event-list > div.event-list__events > a.event-list__events__tile
    fields:
      - name: "location"
        value: Hidén Harlekin
      - name: "city"
        value: "Zug"
      - name: country
        value: Switzerland
      - name: "type"
        value: "concert"
      - name: "sourceUrl"
        value: https://eventfrog.ch/de/events.html?searchTerm=hiden+harlekin+zug
      - name: title
        type: text
        location:
          - selector: div.event-list__events__tile__content > div.event-list__events__tile__content__infos > span.event-list__events__tile__content__infos__title
      - name: imageUrl
        type: url
        location:
          - selector: div.event-list__events__tile__image > img
            attr: src
      - name: url
        type: url
        location:
          - attr: href
      - name: date
        type: date
        components:
          - covers:
              day: true
              month: true
              time: true
            location:
              selector: div.event-list__events__tile__content > div.event-list__events__tile__content__infos > span.event-list__events__tile__content__infos__time
            layout:
              - Monday, 2. January, 15:04
        date_location: CET
        date_language: de_DE
        guess_year: true
