name: scrape_events

on:
  schedule:
    - cron: "0 2 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scrape-all-events:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: crawl-env

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17.8

      # Install go binary
      - name: Install the scraper
        run: go install github.com/jakopako/goskyr@v0.2.10

      # Runs a single command using the runners shell
      - name: Run the scraper
        run: goskyr -config croncert-config.yml
        env:
          WRITER_USER: ${{ secrets.WRITER_USER }}
          WRITER_PASSWORD: ${{ secrets.WRITER_PASSWORD }}
          WRITER_URI: ${{ secrets.WRITER_URI }}
